# Generated by Django 3.0.7 on 2020-06-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amka', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('dose', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('smoker', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('charges', models.FloatField()),
                ('telephone_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'personal_information',
            },
        ),
    ]
