"""
Django settings for insurance project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from .email_info import *
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'aid!k(kz6mj3nf&s2c@ixi+$p_tn3s+yl@jef+eapcs$adzysl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['34.78.215.81']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'insurance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insurance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
	'default': {
    	'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.mysql'),
      'NAME': os.getenv('DATABASE_NAME', 'med_care'),
    	'USER': os.getenv('DATABASE_USER', 'root'),
    	'PASSWORD': os.getenv('DATABASE_PASSWORD', 'password'),
    	'HOST': os.getenv('DATABASE_SERVICE_HOST', '127.0.0.1'),
    	'PORT': os.getenv('DATABASE_SERVICE_PORT', 3306)
    	#'NAME': 'app_db',
    	#'USER': 'app_db_user',
    	#'PASSWORD': 'app_db_pw',
    	#'HOST': 'mysql',
    	#'PORT': '3306'

	}
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
    	'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
    	'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
    	'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
    	'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT-3'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# 'http://34.78.155.148/'
STATIC_URL = 'https://storage.googleapis.com/python_django_apps/'
STATIC_ROOT= os.path.join(BASE_DIR, 'static')

MY_POD_NAME = os.getenv('MY_POD_NAME', 'local')
MY_POD_NAMESPACE = os.getenv('MY_POD_NAMESPACE', 'local')
MY_POD_IP = os.getenv('MY_POD_IP', 'localhost')
